# -*- coding: utf-8 -*-
"""
/***************************************************************************
 T2G_Arch
                                 A QGIS plugin
 Archäologie-PlugIn für Tachy2Gis 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-17
        copyright            : (C) 2019 by Daniel Timmel
        email                :  
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load T2G_Arch class from file T2G_Arch.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .t2g_arch import T2G_Arch
    return T2G_Arch(iface)
