# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeometryCheckDockWidget
                                 A QGIS plugin
 Tool für das Landesamt für Archäologie Dresden
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-29
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Daniel Timmel
        email                : aaa@web.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from os import path as os_path

from qgis.PyQt.QtCore import Qt, pyqtSignal, QVariant
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtWidgets import QDockWidget, QTableWidgetItem
from qgis.PyQt import uic
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsField,
    QgsLayerTreeLayer,
    QgsMarkerSymbol,
    QgsWkbTypes,
    QgsMessageLog,
    Qgis,
    QgsFeature,
    QgsPoint,
    QgsGeometry,
)
from qgis.utils import iface

from ..utils.layers import T2gLayers
from ..utils.functions import delLayer, tableWidgetRemoveRows, isNumber


FORM_CLASS, _ = uic.loadUiType(os_path.join(os_path.dirname(__file__), "geometry_check_dockwidget.ui"))


class GeometryCheckDockWidget(QDockWidget, FORM_CLASS):
    tempLayerName = "Geometrie z-Koord Check"

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(GeometryCheckDockWidget, self).__init__(parent)
        self.setupUi(self)
        self.setAutoFillBackground(True)
        iface.addDockWidget(Qt.TopDockWidgetArea, self)

        self.layer = None
        self.templayer = None
        self.koordList = []

        self.butOK.clicked.connect(self.ok)
        self.butAbbruch.clicked.connect(self.abbruch)
        self.tableWidget.itemChanged.connect(self.vertexEdit)
        self.tableWidget.cellClicked.connect(self.on_cellClicked)
        self.cboLayerName.currentIndexChanged.connect(self.setCheckLayer)

        self.setup()

    def setCheckLayer(self):
        self.layer = QgsProject.instance().mapLayersByName(self.cboLayerName.currentText())[0]
        self.refresh()

    def setup(self):
        layer_list = [T2gLayers.Polygon.value, T2gLayers.Line.value, T2gLayers.Point.value]
        self.cboLayerName.addItems(layer_list)

    def ok(self):
        self.close()

    def abbruch(self):
        self.close()

    def addNewTempLayer(self, crs):
        templayer = QgsVectorLayer("Point", self.tempLayerName, "memory")
        templayer.setCrs(crs)

        templayer.dataProvider().addAttributes([QgsField("id", QVariant.Int, "integer")])
        templayer.updateFields()

        QgsProject.instance().addMapLayer(templayer, False)
        root = QgsProject.instance().layerTreeRoot()
        g = root.findGroup("Vermessung")
        g.insertChildNode(0, QgsLayerTreeLayer(templayer))

        symbol = templayer.renderer().symbol()
        symbol.setColor(QColor.fromRgb(0, 225, 0))
        sym = QgsMarkerSymbol.createSimple({"name": "circle", "color": "red", "size": "3", "outline_width": "1"})
        templayer.renderer().setSymbol(sym)
        templayer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(templayer.id())
        return templayer

    def refresh(self):
        delLayer(self.tempLayerName)
        self.templayer = self.addNewTempLayer(self.layer.crs())
        sel = []
        self.koordList = []
        tableWidgetRemoveRows(self.tableWidget)
        self.tableWidget.setSortingEnabled(False)
        self.templayer.startEditing()

        if self.layer.geometryType() == QgsWkbTypes.PointGeometry:
            for f in self.layer.getFeatures():
                try:
                    koord = {"x": f.geometry().get().x(), "y": f.geometry().get().y(), "z": f.geometry().get().z()}
                    self.koordList.append(koord)
                except Exception as e:
                    QgsMessageLog.logMessage(str(e), "T2G Archäologie", Qgis.Info)
                    sel.append(f.id())
                    # continue

        elif self.layer.geometryType() == QgsWkbTypes.LineGeometry:
            for f in self.layer.getFeatures():
                if f.geometry().isMultipart():
                    parts = f.geometry().asGeometryCollection()
                    for part in parts:
                        for vertex in part.vertices():
                            koord = {"x": vertex.x(), "y": vertex.y(), "z": vertex.z()}
                            self.koordList.append(koord)
                else:
                    try:
                        for i in range(len(f.geometry().asPolyline()[0])):
                            koord = {
                                "x": f.geometry().vertexAt(i).x(),
                                "y": f.geometry().vertexAt(i).y(),
                                "z": f.geometry().vertexAt(i).z(),
                            }
                            self.koordList.append(koord)
                    except:
                        sel.append(f.id())
                        # continue

        elif self.layer.geometryType() == QgsWkbTypes.PolygonGeometry:
            for f in self.layer.getFeatures():
                if f.geometry().isMultipart():
                    parts = f.geometry().asGeometryCollection()
                    for part in parts:
                        for vertex in part.vertices():
                            koord = {"x": vertex.x(), "y": vertex.y(), "z": vertex.z()}
                            self.koordList.append(koord)
                else:
                    try:
                        for i in range(len(f.geometry().asPolygon()[0])):
                            koord = {
                                "x": f.geometry().vertexAt(i).x(),
                                "y": f.geometry().vertexAt(i).y(),
                                "z": f.geometry().vertexAt(i).z(),
                            }
                            self.koordList.append(koord)
                    except:
                        sel.append(f.id())
                        # continue

        # self.layer.selectByIds(sel)
        for i in range(len(self.koordList)):
            self.tableWidget.insertRow(i)
            self.tableWidget.setItem(i, 0, QTableWidgetItem(str(self.koordList[i]["x"])))
            self.tableWidget.setItem(i, 1, QTableWidgetItem(str(self.koordList[i]["y"])))
            self.tableWidget.setItem(i, 2, QTableWidgetItem(str(self.koordList[i]["z"])))
            self.tableWidget.setItem(i, 3, QTableWidgetItem(str(i)))
            feature = QgsFeature()
            pt = QgsPoint(float(self.koordList[i]["x"]), float(self.koordList[i]["y"]), float(self.koordList[i]["z"]))
            feature.setGeometry(QgsGeometry(pt))
            feature.setAttributes([int(i)])
            self.templayer.dataProvider().addFeatures([feature])

        self.tableWidget.setSortingEnabled(True)
        self.labvertexcount.setText(str(len(self.koordList)) + " Punkte")
        self.templayer.updateExtents()
        self.templayer.commitChanges()

    def vertexEdit(self, item):
        # self.layer.changeGeometry(self.feature.id(), newgeom)
        # QgsMessageLog.logMessage(str(item.text()), 'T2G Archäologie', Qgis.Info)
        if isNumber(item.text()):
            if item.column() == 0:
                self.koordList[item.row()]["x"] = item.text()
            if item.column() == 1:
                self.koordList[item.row()]["y"] = item.text()
            if item.column() == 2:
                self.koordList[item.row()]["z"] = item.text()

    def on_cellClicked(self, row, column):
        if self.templayer is None:
            return
        id = self.tableWidget.item(row, 3).text()
        self.templayer.selectByExpression(f"id={id}")
        if self.templayer.selectedFeatureCount():
            iface.mapCanvas().zoomToSelected(self.templayer)
            iface.mapCanvas().zoomByFactor(5)

    def closeEvent(self, event):
        self.dwgClose()
        event.accept()

    def dwgClose(self):
        self.closingPlugin.emit()
        delLayer(self.tempLayerName)
        self.templayer = None
        iface.mapCanvas().refreshAllLayers()
