# -*- coding: utf-8 -*-
"""
/***************************************************************************
 T2G_ArchDockWidget
                                 A QGIS plugin
 Archäologie-PlugIn für Tachy2Gis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-17
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Daniel Timmel
        email                :
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import logging
import os

from qgis.PyQt.QtWidgets import QDockWidget
from qgis.PyQt import uic

from .geoEdit.geo_edit import GeoEdit
from .messen.messen import MeasurementTab
from .profile.profile import Profile
from .raster.widgets import RasterGui
from .tools_allgemein.widgets import ToolsAllgemeinTab
from .transformation.transformation_gui import TransformationGui
from ..common.utils import set_vsi_cached, ArchProjectConfig
from ..settings import DEBUG

LOGGER = logging.getLogger(__name__)
FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "forms", "t2g_arch_dockwidget.ui"))


class T2GArchDockWidget(QDockWidget, FORM_CLASS):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.measurementTab = None
        self.toolsAllgemeinTab = None
        self.transformationGui = None
        self.geoEdit = None
        self.profile = None
        self.raster = None

        self.setupUi(self)
        self.setupModules()
        self.tabWidget.setCurrentIndex(0)

    def setupModules(self):
        # Messen
        self.measurementTab = MeasurementTab()
        self.tab_measurement.layout().addWidget(self.measurementTab)

        # Tools Allgemein
        self.toolsAllgemeinTab = ToolsAllgemeinTab()
        self.tab_tools_allgemein.layout().addWidget(self.toolsAllgemeinTab)

        # Transformation
        self.transformationGui = TransformationGui(self)
        self.transformationGui.setup()

        # Geometriebearbeitung
        self.geoEdit = GeoEdit(self)
        self.geoEdit.setup()

        # Profile
        self.profile = Profile(self)
        self.profile.setup()

        # Raster
        self.raster = RasterGui(self)
        self.raster.setup()

    def unload(self):
        if DEBUG:
            from ..common.debug_checks import check_for_surviving_instances
            check_for_surviving_instances(
                self.transformationGui,
                self.geoEdit,
                self.profile,
                self.raster,
                context="T2GArchDockWidget.unload()",
            )

        # Transformation
        if self.transformationGui:
            self.transformationGui.disconnectSignals()
        self.transformationGui = None

        # Geometriebearbeitung
        if self.geoEdit:
            self.geoEdit.disconnectSignals()
        self.geoEdit = None

        # Profile
        self.profile = None

        # Messen
        if self.measurementTab:
            self.measurementTab.closeMeasurementTab()

        # Raster
        self.raster = None

        set_vsi_cached(False)

        ArchProjectConfig.clear()

    def deleteLater(self):
        # measurementTab itself is a Qt child (added via layout) and is cascade-deleted
        # with this widget. helpWindow has no parent (see debug_checks fix), so it needs
        # an explicit, one-time deleteLater() here instead of in unload()/closeMeasurementTab(),
        # which can run repeatedly while the plugin is still active (e.g. on project switch).
        self.measurementTab.helpWindow.deleteLater()
        # same one-time situation for the shortcuts parented to iface.mapCanvas()
        self.measurementTab.removeKeys()
        super().deleteLater()

    def reload(self):
        if self.geoEdit:
            self.geoEdit.disconnectSignals()
        if self.transformationGui:
            self.transformationGui.disconnectSignals()

        if DEBUG:
            from ..common.debug_checks import check_for_surviving_instances
            check_for_surviving_instances(
                self.transformationGui,
                self.geoEdit,
                self.profile,
                self.raster,
                context="T2GArchDockWidget.reload()",
            )

        # Transformation
        self.transformationGui = TransformationGui(self)
        self.transformationGui.setup()

        # Geometriebearbeitung
        self.geoEdit = GeoEdit(self)
        self.geoEdit.setup()

        # Profile
        self.profile = Profile(self)
        self.profile.setup()

        # Messen
        self.measurementTab.resetMeasurementTab()

        # Raster
        self.raster = RasterGui(self)
        self.raster.setup()
