# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeometryCheckDockWidget
                                 A QGIS plugin
 Tool für das Landesamt für Archäologie Dresden
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-29
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Daniel Timmel
        email                : aaa@web.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from dataclasses import dataclass
from os import path as os_path

from qgis.PyQt.QtCore import Qt, pyqtSignal, QVariant, QLocale
from qgis.PyQt.QtGui import QBrush, QColor, QDoubleValidator
from qgis.PyQt.QtWidgets import QDockWidget, QLineEdit, QTableWidgetItem, QStyledItemDelegate
from qgis.PyQt import uic
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsField,
    QgsLayerTreeLayer,
    QgsMarkerSymbol,
    QgsWkbTypes,
    QgsMessageLog,
    Qgis,
    QgsFeature,
    QgsPoint,
    QgsGeometry,
    QgsVertexId,
)
from qgis.utils import iface, OverrideCursor

from ...settings import PLUGIN_NAME
from ...common.layers import T2gLayers
from ...common.utils import delLayer, tableWidgetRemoveRows, isNumber


class NumericTableWidgetItem(QTableWidgetItem):
    def __lt__(self, other):
        try:
            return float(self.text()) < float(other.text())
        except ValueError:
            return super().__lt__(other)


class FixupDoubleValidator(QDoubleValidator):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setLocale(QLocale(QLocale.C))
        self.setNotation(QDoubleValidator.StandardNotation)

    def validate(self, inputStr, pos):
        state, text, pos = super().validate(inputStr.replace(",", "."), pos)
        return state, inputStr, pos


class NumericDelegate(QStyledItemDelegate):
    def createEditor(self, parent, option, index):
        editor = QLineEdit(parent)
        editor.setValidator(FixupDoubleValidator(editor))
        return editor

    def setEditorData(self, editor, index):
        value = index.data(Qt.EditRole)
        if value is not None:
            editor.setText(str(value))

    def setModelData(self, editor, model, index):
        text = editor.text().replace(",", ".")
        try:
            value = float(text)
            model.setData(index, value, Qt.EditRole)
        except ValueError:
            previousValue = index.data(Qt.EditRole)
            editor.setText(str(previousValue))

    def displayText(self, value, locale):
        try:
            return str(value)
        except (ValueError, TypeError):
            return super().displayText(value, locale)


@dataclass
class VertexCoordinate:
    x: float
    y: float
    z: float
    featureId: int
    vertexId: QgsVertexId


FORM_CLASS, _ = uic.loadUiType(os_path.join(os_path.dirname(__file__), "geometry_check_dockwidget.ui"))


class GeometryCheckDockWidget(QDockWidget, FORM_CLASS):
    tempLayerName = "Geometrie z-Koord Check"

    closingPlugin = pyqtSignal()

    columnX = 0
    columnY = 1
    columnZ = 2
    columnTempId = 3

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.setAutoFillBackground(True)
        iface.addDockWidget(Qt.TopDockWidgetArea, self)

        self.layer = None
        self.templayer = None
        self.koordList: list[VertexCoordinate] = []
        self.changedCoordIds: set[int] = set()
        self.hasChanges = False

        self.butOK.clicked.connect(self.applyAndClose)
        self.butAbbruch.clicked.connect(self.close)
        self.butApply.clicked.connect(self.applyChanges)
        self.tableWidget.itemChanged.connect(self.vertexEdit)
        self.tableWidget.selectionModel().currentRowChanged.connect(self._onCurrentRowChanged)
        self.cboLayerName.currentIndexChanged.connect(self.setCheckLayer)
        self.tableWidget.setItemDelegate(NumericDelegate())

        self.setup()

    def setCheckLayer(self):
        self.layer = QgsProject.instance().mapLayersByName(self.cboLayerName.currentText())[0]
        self.refresh()

    def setup(self):
        layerList = [T2gLayers.Polygon.value, T2gLayers.Line.value, T2gLayers.Point.value]
        self.cboLayerName.addItems(layerList)

    def applyAndClose(self):
        self.applyChanges()
        self.close()

    def applyChanges(self):
        if not self.hasChanges or not self.layer:
            return

        self.layer.startEditing()

        for koordId in self.changedCoordIds:
            koord = self.koordList[koordId]
            feature = self.layer.getFeature(koord.featureId)
            geom = feature.geometry()

            new_point = QgsPoint(koord.x, koord.y, koord.z)
            geom.get().moveVertex(koord.vertexId, new_point)
            self.layer.changeGeometry(koord.featureId, geom)

        self.layer.commitChanges()
        iface.mapCanvas().redrawAllLayers()
        self.hasChanges = False
        self.changedCoordIds.clear()
        self.refresh()

    def addNewTempLayer(self, crs):
        templayer = QgsVectorLayer("Point", self.tempLayerName, "memory")
        templayer.setCrs(crs)

        templayer.dataProvider().addAttributes([QgsField("id", QVariant.Int, "integer")])
        templayer.updateFields()

        QgsProject.instance().addMapLayer(templayer, False)
        root = QgsProject.instance().layerTreeRoot()
        g = root.findGroup("Vermessung")
        g.insertChildNode(0, QgsLayerTreeLayer(templayer))

        sym = QgsMarkerSymbol.createSimple({"name": "circle", "color": "red", "size": "3", "outline_width": "1"})
        templayer.renderer().setSymbol(sym)
        templayer.triggerRepaint()
        iface.layerTreeView().refreshLayerSymbology(templayer.id())
        return templayer

    def refresh(self):
        with OverrideCursor(Qt.WaitCursor):
            delLayer(self.tempLayerName)
            self.templayer = self.addNewTempLayer(self.layer.crs())
            self.koordList = []
            self.changedCoordIds.clear()
            tableWidgetRemoveRows(self.tableWidget)
            self.tableWidget.setSortingEnabled(False)

            if self.layer.geometryType() == QgsWkbTypes.PointGeometry:
                for f in self.layer.getFeatures():
                    try:
                        geom = f.geometry().get()
                        koord = VertexCoordinate(
                            x=geom.x(), y=geom.y(), z=geom.z(), featureId=f.id(), vertexId=QgsVertexId(0, 0, 0)
                        )
                        self.koordList.append(koord)
                    except Exception as e:
                        QgsMessageLog.logMessage(str(e), PLUGIN_NAME, Qgis.Info)

            elif self.layer.geometryType() in (QgsWkbTypes.LineGeometry, QgsWkbTypes.PolygonGeometry):
                for f in self.layer.getFeatures():
                    self._extractVerticesFromFeature(f)

            self.tableWidget.blockSignals(True)
            tempFeatures = []
            for i in range(len(self.koordList)):
                vertexCoordinate = self.koordList[i]
                self.tableWidget.insertRow(i)
                self.tableWidget.setItem(i, self.columnX, NumericTableWidgetItem(str(vertexCoordinate.x)))
                self.tableWidget.setItem(i, self.columnY, NumericTableWidgetItem(str(vertexCoordinate.y)))
                self.tableWidget.setItem(i, self.columnZ, NumericTableWidgetItem(str(vertexCoordinate.z)))
                itemId = NumericTableWidgetItem(str(i))
                itemId.setFlags(itemId.flags() & ~Qt.ItemIsEditable)
                self.tableWidget.setItem(i, self.columnTempId, itemId)

                feature = QgsFeature()
                pt = QgsPoint(vertexCoordinate.x, vertexCoordinate.y, vertexCoordinate.z)
                feature.setGeometry(QgsGeometry(pt))
                feature.setAttributes([int(i)])
                tempFeatures.append(feature)

            self.templayer.dataProvider().addFeatures(tempFeatures)
            self.tableWidget.blockSignals(False)
            self.tableWidget.setSortingEnabled(True)
            self.labvertexcount.setText(str(len(self.koordList)) + " Punkte")
            self.templayer.updateExtents()

    def vertexEdit(self, item):
        newValue = item.data(Qt.EditRole)
        if not isNumber(newValue):
            return

        row = item.row()
        col = item.column()
        koordId = int(self.tableWidget.item(row, self.columnTempId).text())
        oldValue = {
            self.columnX: self.koordList[koordId].x,
            self.columnY: self.koordList[koordId].y,
            self.columnZ: self.koordList[koordId].z,
        }.get(col)
        if oldValue == newValue:
            return

        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.blockSignals(True)

        if col == self.columnX:
            self.koordList[koordId].x = item.data(Qt.EditRole)
            self._markCellAsChanged(item, koordId)
        elif col == self.columnY:
            self.koordList[koordId].y = item.data(Qt.EditRole)
            self._markCellAsChanged(item, koordId)
        elif col == self.columnZ:
            self.koordList[koordId].z = item.data(Qt.EditRole)
            self._markCellAsChanged(item, koordId)

        self.tableWidget.blockSignals(False)
        self.tableWidget.setSortingEnabled(True)

    def _markCellAsChanged(self, item, koord_id):
        item.setBackground(QBrush(QColor(255, 255, 150)))
        self.changedCoordIds.add(koord_id)
        self.hasChanges = True

    def _extractVerticesFromFeature(self, feature):
        fid = feature.id()
        geom = feature.geometry()
        for i, vertex in enumerate(geom.vertices()):
            exists, vertex_id = geom.vertexIdFromVertexNr(i)
            koord = VertexCoordinate(x=vertex.x(), y=vertex.y(), z=vertex.z(), featureId=fid, vertexId=vertex_id)
            self.koordList.append(koord)

    def _onCurrentRowChanged(self, current, previous):
        if self.templayer is None or not current.isValid():
            return
        _id = self.tableWidget.item(current.row(), self.columnTempId).text()
        self.templayer.selectByExpression(f"id={_id}")
        if self.templayer.selectedFeatureCount():
            iface.mapCanvas().panToSelected(self.templayer)
            iface.mapCanvas().flashFeatureIds(self.templayer, self.templayer.selectedFeatureIds(), flashes=1)

    def closeEvent(self, event):
        self.dwgClose()
        event.accept()

    def dwgClose(self):
        self.closingPlugin.emit()
        delLayer(self.tempLayerName)
        self.templayer = None
        iface.mapCanvas().refreshAllLayers()
